name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run coverage report
        run: npm run test:coverage

      - name: Upload coverage to GitHub summary
        if: success()
        run: |
          echo '### Test Coverage' >> $GITHUB_STEP_SUMMARY
          npx jest --coverage --coverageReporters=text >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
